import { Injectable } from '@angular/core';
declare let alertify: any;

@Injectable({
  providedIn: 'root'
})
export class AlertifyService {
  constructor() {}

  confirm(message: string, okCallback: () => any) {
    alertify.confirm(message, (e: any) => {
        if (e) {
          okCallback();
        } else { }
      });
  }

  success(message: string) {
    alertify.success(message);0
  }

  error(message: string) {
    alertify.error(message);
  }

  warning(message: string) {
    alertify.warning(message);
  }

  message(message: string) {
    alertify.message(message);
  }
  
  Government() {
    return [
      { id: 'Cairo', name: 'Cairo' },
      { id: 'Giza', name: 'Giza' },
      { id: 'Alexandria', name: 'Alexandria' },
      { id: 'Dakahlia', name: 'Dakahlia' },
      { id: 'Red Sea', name: 'Red Sea' },
      { id: 'Beheira', name: 'Beheira' },
      { id: 'Fayoum', name: 'Fayoum' },
      { id: 'Gharbiya', name: 'Gharbiya' },
      { id: 'Ismailia', name: 'Ismailia' },
      { id: 'Menofia', name: 'Menofia' },
      { id: 'Minya', name: 'Minya' },
      { id: 'Qaliubiya', name: 'Qaliubiya' },
      { id: 'New Valley', name: 'New Valley' },
      { id: 'Suez', name: 'Suez' },
      { id: 'Aswan', name: 'Aswan' },
      { id: 'Assiut', name: 'Assiut' },
      { id: 'Beni Suef', name: 'Beni Suef' },
      { id: 'Port Said', name: 'Port Said' },
      { id: 'Damietta', name: 'Damietta' },
      { id: 'Sharkia', name: 'Sharkia' },
      { id: 'South Sinai', name: 'South Sinai' },
      { id: 'Kafr Al sheikh', name: 'Kafr Al sheikh' },
      { id: 'Matrouh', name: 'Matrouh' },
      { id: 'Luxor', name: 'Luxor' },
      { id: 'Qena', name: 'Qena' },
      { id: 'North Sinai', name: 'North Sinai' },
      { id: 'Sohag', name: 'Sohag' },
    ];
  }

  city() {
    return [
      { id: 'Cairo', name: '15 May' },
      { id: 'Cairo', name: 'Al Azbakeyah' },
      { id: 'Cairo', name: 'Al Basatin' },
      { id: 'Cairo', name: 'Tebin' },
      { id: 'Cairo', name: 'El-Khalifa' },
      { id: 'Cairo', name: 'El darrasa' },
      { id: 'Cairo', name: 'Aldarb Alahmar' },
      { id: 'Cairo', name: 'Zawya al-Hamra' },
      { id: 'Cairo', name: 'El-Zaytoun' },
      { id: 'Cairo', name: 'Sahel' },
      { id: 'Cairo', name: 'El Salam' },
      { id: 'Cairo', name: 'Sayeda Zeinab' },
      { id: 'Cairo', name: 'El Sharabeya' },
      { id: 'Cairo', name: 'Shorouk' },
      { id: 'Cairo', name: 'El Daher' },
      { id: 'Cairo', name: 'Ataba' },
      { id: 'Cairo', name: 'New Cairo' },
      { id: 'Cairo', name: 'El Marg' },
      { id: 'Cairo', name: 'Ezbet el Nakhl' },
      { id: 'Cairo', name: 'Matareya' },
      { id: 'Cairo', name: 'Maadi' },
      { id: 'Cairo', name: 'Maasara' },
      { id: 'Cairo', name: 'Mokattam' },
      { id: 'Cairo', name: 'Manyal' },
      { id: 'Cairo', name: 'Mosky' },
      { id: 'Cairo', name: 'Nozha' },
      { id: 'Cairo', name: 'Waily' },
      { id: 'Cairo', name: 'Bab al-Shereia' },
      { id: 'Cairo', name: 'Bolaq' },
      { id: 'Cairo', name: 'Garden City' },
      { id: 'Cairo', name: 'Hadayek El-Kobba' },
      { id: 'Cairo', name: 'Helwan' },
      { id: 'Cairo', name: 'Dar Al Salam' },
      { id: 'Cairo', name: 'Shubra' },
      { id: 'Cairo', name: 'Tura' },
      { id: 'Cairo', name: 'Abdeen' },
      { id: 'Cairo', name: 'Abaseya' },
      { id: 'Cairo', name: 'Ain Shams' },
      { id: 'Cairo', name: 'Nasr City' },
      { id: 'Cairo', name: 'New Heliopolis' },
      { id: 'Cairo', name: 'Masr Al Qadima' },
      { id: 'Cairo', name: 'Mansheya Nasir' },
      { id: 'Cairo', name: 'Badr City' },
      { id: 'Cairo', name: 'Obour City' },
      { id: 'Cairo', name: 'Cairo Downtown' },
      { id: 'Cairo', name: 'Zamalek' },
      { id: 'Cairo', name: 'Kasr El Nile' },
      { id: 'Cairo', name: 'Rehab' },
      { id: 'Cairo', name: 'Katameya' },
      { id: 'Cairo', name: 'Madinty' },
      { id: 'Cairo', name: 'Rod Alfarag' },
      { id: 'Cairo', name: 'Sheraton' },
      { id: 'Cairo', name: 'El-Gamaleya' },
      { id: 'Cairo', name: '10th of Ramadan City' },
      { id: 'Cairo', name: 'Helmeyat Alzaytoun' },
      { id: 'Cairo', name: 'New Nozha' },
      { id: 'Cairo', name: 'Capital New' },
      { id: 'Giza', name: 'Giza' },
      { id: 'Giza', name: 'Sixth of October' },
      { id: 'Giza', name: 'Cheikh Zayed' },
      { id: 'Giza', name: 'Hawamdiyah' },
      { id: 'Giza', name: 'Al Badrasheen' },
      { id: 'Giza', name: 'Saf' },
      { id: 'Giza', name: 'Atfih' },
      { id: 'Giza', name: 'Al Ayat' },
      { id: 'Giza', name: 'Al-Bawaiti' },
      { id: 'Giza', name: 'ManshiyetAl Qanater' },
      { id: 'Giza', name: 'Oaseem' },
      { id: 'Giza', name: 'Kerdasa' },
      { id: 'Giza', name: 'Abu Nomros' },
      { id: 'Giza', name: 'Kafr Ghati' },
      { id: 'Giza', name: 'Manshiyet Al Bakari' },
      { id: 'Giza', name: 'Dokki' },
      { id: 'Giza', name: 'Agouza' },
      { id: 'Giza', name: 'Haram' },
      { id: 'Giza', name: 'Warraq' },
      { id: 'Giza', name: 'Imbaba' },
      { id: 'Giza', name: 'Boulaq Dakrour' },
      { id: 'Giza', name: 'Al Wahat Al Baharia' },
      { id: 'Giza', name: 'Omraneya' },
      { id: 'Giza', name: 'Moneeb' },
      { id: 'Giza', name: 'Bin Alsarayat' },
      { id: 'Giza', name: 'Kit Kat' },
      { id: 'Giza', name: 'Mohandessin' },
      { id: 'Giza', name: 'Faisal' },
      { id: 'Giza', name: 'Abu Rawash' },
      { id: 'Giza', name: 'Hadayek Alahram' },
      { id: 'Giza', name: 'Haraneya' },
      { id: 'Giza', name: 'Hadayek October' },
      { id: 'Giza', name: 'Saft Allaban' },
      { id: 'Giza', name: 'Smart Village' },
      { id: 'Giza', name: 'Ard Ellwaa' },
      { id: 'Alexandria', name: 'Abu Qir' },
      { id: 'Alexandria', name: 'Al Ibrahimeyah' },
      { id: 'Alexandria', name: 'Azarita' },
      { id: 'Alexandria', name: 'Anfoushi' },
      { id: 'Alexandria', name: 'Dekheila' },
      { id: 'Alexandria', name: 'El Soyof' },
      { id: 'Alexandria', name: 'Ameria' },
      { id: 'Alexandria', name: 'El Labban' },
      { id: 'Alexandria', name: 'Al Mafrouza' },
      { id: 'Alexandria', name: 'El Montaza' },
      { id: 'Alexandria', name: 'Mansheya' },
      { id: 'Alexandria', name: 'Naseria' },
      { id: 'Alexandria', name: 'Ambrozo' },
      { id: 'Alexandria', name: 'Bab Sharq' },
      { id: 'Alexandria', name: 'Bourj Alarab' },
      { id: 'Alexandria', name: 'Stanley' },
      { id: 'Alexandria', name: 'Smouha' },
      { id: 'Alexandria', name: 'Sidi Bishr' },
      { id: 'Alexandria', name: 'Shads' },
      { id: 'Alexandria', name: 'Gheet Alenab' },
      { id: 'Alexandria', name: 'Fleming' },
      { id: 'Alexandria', name: 'Victoria' },
      { id: 'Alexandria', name: 'Camp Shizar' },
      { id: 'Alexandria', name: 'Karmooz' },
      { id: 'Alexandria', name: 'Mahta Alraml' },
      { id: 'Alexandria', name: 'Mina El-Basal' },
      { id: 'Alexandria', name: 'Asafra' },
      { id: 'Alexandria', name: 'Agamy' },
      { id: 'Alexandria', name: 'Bakos' },
      { id: 'Alexandria', name: 'Boulkly' },
      { id: 'Alexandria', name: 'Cleopatra' },
      { id: 'Alexandria', name: 'Glim' },
      { id: 'Alexandria', name: 'Al Mamurah' },
      { id: 'Alexandria', name: 'Al Mandara' },
      { id: 'Alexandria', name: 'Moharam Bek' },
      { id: 'Alexandria', name: 'Elshatby' },
      { id: 'Alexandria', name: 'Sidi Gaber' },
      { id: 'Alexandria', name: 'North Coast/sahel' },
      { id: 'Alexandria', name: 'Alhadra' },
      { id: 'Alexandria', name: 'Alattarin' },
      { id: 'Alexandria', name: 'Sidi Kerir' },
      { id: 'Alexandria', name: 'Elgomrok' },
      { id: 'Alexandria', name: 'Al Max' },
      { id: 'Alexandria', name: 'Marina' },
      { id: 'Dakahlia', name: 'Mansoura' },
      { id: 'Dakahlia', name: 'Talkha' },
      { id: 'Dakahlia', name: 'Mitt Ghamr' },
      { id: 'Dakahlia', name: 'Dekernes' },
      { id: 'Dakahlia', name: 'Aga' },
      { id: 'Dakahlia', name: 'Menia El Nasr' },
      { id: 'Dakahlia', name: 'Sinbillawin' },
      { id: 'Dakahlia', name: 'El Kurdi' },
      { id: 'Dakahlia', name: 'Bani Ubaid' },
      { id: 'Dakahlia', name: 'Al Manzala' },
      { id: 'Dakahlia', name: "tami al'amdid" },
      { id: 'Dakahlia', name: 'aljamalia' },
      { id: 'Dakahlia', name: 'Sherbin' },
      { id: 'Dakahlia', name: 'Mataria' },
      { id: 'Dakahlia', name: 'Belqas' },
      { id: 'Dakahlia', name: 'Meet Salsil' },
      { id: 'Dakahlia', name: 'Gamasa' },
      { id: 'Dakahlia', name: 'Mahalat Damana' },
      { id: 'Dakahlia', name: 'Nabroh' },
      { id: 'Red Sea', name: 'Hurghada' },
      { id: 'Red Sea', name: 'Ras Ghareb' },
      { id: 'Red Sea', name: 'Safaga' },
      { id: 'Red Sea', name: 'El Qusiar' },
      { id: 'Red Sea', name: 'Marsa Alam' },
      { id: 'Red Sea', name: 'Shalatin' },
      { id: 'Red Sea', name: 'Halaib' },
      { id: 'Red Sea', name: 'Aldahar' },
      { id: 'Beheira', name: 'Damanhour' },
      { id: 'Beheira', name: 'Kafr El Dawar' },
      { id: 'Beheira', name: 'Rashid' },
      { id: 'Beheira', name: 'Edco' },
      { id: 'Beheira', name: 'Abu al-Matamir' },
      { id: 'Beheira', name: 'Abu Homs' },
      { id: 'Beheira', name: 'Delengat' },
      { id: 'Beheira', name: 'Mahmoudiyah' },
      { id: 'Beheira', name: 'Rahmaniyah' },
      { id: 'Beheira', name: 'Itai Baroud' },
      { id: 'Beheira', name: 'Housh Eissa' },
      { id: 'Beheira', name: 'Shubrakhit' },
      { id: 'Beheira', name: 'Kom Hamada' },
      { id: 'Beheira', name: 'Badr' },
      { id: 'Beheira', name: 'Wadi Natrun' },
      { id: 'Beheira', name: 'New Nubaria' },
      { id: 'Beheira', name: 'Alnoubareya' },
      { id: 'Fayoum', name: 'Fayoum' },
      { id: 'Fayoum', name: 'Fayoum El Gedida' },
      { id: 'Fayoum', name: 'Tamiya' },
      { id: 'Fayoum', name: 'Snores' },
      { id: 'Fayoum', name: 'Etsa' },
      { id: 'Fayoum', name: 'Epschway' },
      { id: 'Fayoum', name: 'Yusuf El Sediaq' },
      { id: 'Fayoum', name: 'Hadqa' },
      { id: 'Fayoum', name: 'Atsa' },
      { id: 'Fayoum', name: 'Algamaa' },
      { id: 'Fayoum', name: 'Sayala' },
      { id: 'Gharbiya', name: 'Tanta' },
      { id: 'Gharbiya', name: 'Al Mahalla Al Kobra' },
      { id: 'Gharbiya', name: 'Kafr El Zayat' },
      { id: 'Gharbiya', name: 'Zefta' },
      { id: 'Gharbiya', name: 'El Santa' },
      { id: 'Gharbiya', name: 'Qutour' },
      { id: 'Gharbiya', name: 'Basion' },
      { id: 'Gharbiya', name: 'Samannoud' },
      { id: 'Ismailia', name: 'Ismailia' },
      { id: 'Ismailia', name: 'Fayed' },
      { id: 'Ismailia', name: 'Qantara Sharq' },
      { id: 'Ismailia', name: 'Qantara Gharb' },
      { id: 'Ismailia', name: 'El Tal El Kabier' },
      { id: 'Ismailia', name: 'Abu Sawir' },
      { id: 'Ismailia', name: 'Kasasien El Gedida' },
      { id: 'Ismailia', name: 'Nefesha' },
      { id: 'Ismailia', name: 'Sheikh Zayed' },
      { id: 'Menofia', name: 'Shbeen El Koom' },
      { id: 'Menofia', name: 'Sadat City' },
      { id: 'Menofia', name: 'Menouf' },
      { id: 'Menofia', name: 'Sars El-Layan' },
      { id: 'Menofia', name: 'Ashmon' },
      { id: 'Menofia', name: 'Al Bagor' },
      { id: 'Menofia', name: 'Quesna' },
      { id: 'Menofia', name: 'Berkat El Saba' },
      { id: 'Menofia', name: 'Tala' },
      { id: 'Menofia', name: 'Al Shohada' },
      { id: 'Minya', name: 'Minya' },
      { id: 'Minya', name: 'Minya El Gedida' },
      { id: 'Minya', name: 'El Adwa' },
      { id: 'Minya', name: 'Magagha' },
      { id: 'Minya', name: 'Bani Mazar' },
      { id: 'Minya', name: 'Mattay' },
      { id: 'Minya', name: 'Samalut' },
      { id: 'Minya', name: 'Madinat El Fekria' },
      { id: 'Minya', name: 'Meloy' },
      { id: 'Minya', name: 'Deir Mawas' },
      { id: 'Minya', name: 'Abu Qurqas' },
      { id: 'Minya', name: 'Ard Sultan' },
      { id: 'Qaliubiya', name: 'Banha' },
      { id: 'Qaliubiya', name: 'Qalyub' },
      { id: 'Qaliubiya', name: 'Shubra Al Khaimah' },
      { id: 'Qaliubiya', name: 'Al Qanater Charity' },
      { id: 'Qaliubiya', name: 'Khanka' },
      { id: 'Qaliubiya', name: 'Kafr Shukr' },
      { id: 'Qaliubiya', name: 'Tukh' },
      { id: 'Qaliubiya', name: 'Qaha' },
      { id: 'Qaliubiya', name: 'Obour' },
      { id: 'Qaliubiya', name: 'Khosous' },
      { id: 'Qaliubiya', name: 'Shibin Al Qanater' },
      { id: 'Qaliubiya', name: 'Mostorod' },
      { id: 'New Valley', name: 'El Kharga' },
      { id: 'New Valley', name: 'Paris' },
      { id: 'New Valley', name: 'Mout' },
      { id: 'New Valley', name: 'Farafra' },
      { id: 'New Valley', name: 'Balat' },
      { id: 'New Valley', name: 'Dakhla' },
      { id: 'Suez', name: 'Suez' },
      { id: 'Suez', name: 'Alganayen' },
      { id: 'Suez', name: 'Ataqah' },
      { id: 'Suez', name: 'Ain Sokhna' },
      { id: 'Suez', name: 'Faysal' },
      { id: 'Aswan', name: 'Aswan' },
      { id: 'Aswan', name: 'Aswan El Gedida' },
      { id: 'Aswan', name: 'Drau' },
      { id: 'Aswan', name: 'Kom Ombo' },
      { id: 'Aswan', name: 'Nasr Al Nuba' },
      { id: 'Aswan', name: 'Kalabsha' },
      { id: 'Aswan', name: 'Edfu' },
      { id: 'Aswan', name: 'Al-Radisiyah' },
      { id: 'Aswan', name: 'Al Basilia' },
      { id: 'Aswan', name: 'Al Sibaeia' },
      { id: 'Aswan', name: 'Abo Simbl Al Siyahia' },
      { id: 'Aswan', name: 'Marsa Alam' },
      { id: 'Assiut', name: 'Assiut' },
      { id: 'Assiut', name: 'Assiut El Gedida' },
      { id: 'Assiut', name: 'Dayrout' },
      { id: 'Assiut', name: 'Manfalut' },
      { id: 'Assiut', name: 'Qusiya' },
      { id: 'Assiut', name: 'Abnoub' },
      { id: 'Assiut', name: 'Abu Tig' },
      { id: 'Assiut', name: 'El Ghanaim' },
      { id: 'Assiut', name: 'Sahel Selim' },
      { id: 'Assiut', name: 'El Badari' },
      { id: 'Assiut', name: 'Sidfa' },
      { id: 'Beni Suef', name: 'Bani Sweif' },
      { id: 'Beni Suef', name: 'Beni Suef El Gedida' },
      { id: 'Beni Suef', name: 'Al Wasta' },
      { id: 'Beni Suef', name: 'Naser' },
      { id: 'Beni Suef', name: 'Ehnasia' },
      { id: 'Beni Suef', name: 'beba' },
      { id: 'Beni Suef', name: 'Fashn' },
      { id: 'Beni Suef', name: 'Somasta' },
      { id: 'Beni Suef', name: 'Alabbaseri' },
      { id: 'Beni Suef', name: 'Mokbel' },
      { id: 'Port Said', name: 'PorSaid' },
      { id: 'Port Said', name: 'Port Fouad' },
      { id: 'Port Said', name: 'Alarab' },
      { id: 'Port Said', name: 'Zohour' },
      { id: 'Port Said', name: 'Alsharq' },
      { id: 'Port Said', name: 'Aldawahi' },
      { id: 'Port Said', name: 'Almanakh' },
      { id: 'Port Said', name: 'Mubarak' },
      { id: 'Damietta', name: 'Damietta' },
      { id: 'Damietta', name: 'New Damietta' },
      { id: 'Damietta', name: 'Ras El Bar' },
      { id: 'Damietta', name: 'Faraskour' },
      { id: 'Damietta', name: 'Zarqa' },
      { id: 'Damietta', name: 'alsaru' },
      { id: 'Damietta', name: 'alruwda' },
      { id: 'Damietta', name: 'Kafr El-Batikh' },
      { id: 'Damietta', name: 'Azbet Al Burg' },
      { id: 'Damietta', name: 'Meet Abou Ghalib' },
      { id: 'Damietta', name: 'Kafr Saad' },
      { id: 'Sharkia', name: 'Zagazig' },
      { id: 'Sharkia', name: 'Al Ashr Men Ramadan' },
      { id: 'Sharkia', name: 'Minya Al Qamh' },
      { id: 'Sharkia', name: 'Belbeis' },
      { id: 'Sharkia', name: 'Mashtoul El Souq' },
      { id: 'Sharkia', name: 'Qenaiat' },
      { id: 'Sharkia', name: 'Abu Hammad' },
      { id: 'Sharkia', name: 'El Qurain' },
      { id: 'Sharkia', name: 'Hehia' },
      { id: 'Sharkia', name: 'Abu Kabir' },
      { id: 'Sharkia', name: 'Faccus' },
      { id: 'Sharkia', name: 'El Salihia El Gedida' },
      { id: 'Sharkia', name: 'Al Ibrahimiyah' },
      { id: 'Sharkia', name: 'Deirb Negm' },
      { id: 'Sharkia', name: 'Kafr Saqr' },
      { id: 'Sharkia', name: 'Awlad Saqr' },
      { id: 'Sharkia', name: 'Husseiniya' },
      { id: 'Sharkia', name: 'san alhajar alqablia' },
      { id: 'Sharkia', name: 'Manshayat Abu Omar' },
      { id: 'South Sinai', name: 'Al Toor' },
      { id: 'South Sinai', name: 'Sharm El-Shaikh' },
      { id: 'South Sinai', name: 'Dahab' },
      { id: 'South Sinai', name: 'Nuweiba' },
      { id: 'South Sinai', name: 'Taba' },
      { id: 'South Sinai', name: 'Saint Catherine' },
      { id: 'South Sinai', name: 'Abu Redis' },
      { id: 'South Sinai', name: 'Abu Zenaima' },
      { id: 'South Sinai', name: 'Ras Sidr' },
      { id: 'Kafr Al sheikh', name: 'Kafr El Sheikh' },
      { id: 'Kafr Al sheikh', name: 'Kafr El Sheikh Downtown' },
      { id: 'Kafr Al sheikh', name: 'Desouq' },
      { id: 'Kafr Al sheikh', name: 'Fooh' },
      { id: 'Kafr Al sheikh', name: 'Metobas' },
      { id: 'Kafr Al sheikh', name: 'Burg Al Burullus' },
      { id: 'Kafr Al sheikh', name: 'Baltim' },
      { id: 'Kafr Al sheikh', name: 'Masief Baltim' },
      { id: 'Kafr Al sheikh', name: 'Hamol' },
      { id: 'Kafr Al sheikh', name: 'Bella' },
      { id: 'Kafr Al sheikh', name: 'Riyadh' },
      { id: 'Kafr Al sheikh', name: 'Sidi Salm' },
      { id: 'Kafr Al sheikh', name: 'Qellen' },
      { id: 'Kafr Al sheikh', name: 'Sidi Ghazi' },
      { id: 'Matrouh', name: 'Marsa Matrouh' },
      { id: 'Matrouh', name: 'El Hamam' },
      { id: 'Matrouh', name: 'Alamein' },
      { id: 'Matrouh', name: 'Dabaa' },
      { id: 'Matrouh', name: 'Al-Nagila' },
      { id: 'Matrouh', name: 'Sidi Brani' },
      { id: 'Matrouh', name: 'Salloum' },
      { id: 'Matrouh', name: 'Siwa' },
      { id: 'Matrouh', name: 'Marina' },
      { id: 'Matrouh', name: 'North Coast' },
      { id: 'Luxor', name: 'Luxor' },
      { id: 'Luxor', name: 'New Luxor' },
      { id: 'Luxor', name: 'Esna' },
      { id: 'Luxor', name: 'New Tiba' },
      { id: 'Luxor', name: 'Al ziynia' },
      { id: 'Luxor', name: 'Al Bayadieh' },
      { id: 'Luxor', name: 'Al Qarna' },
      { id: 'Luxor', name: 'Armant' },
      { id: 'Luxor', name: 'Al Tud' },
      { id: 'Qena', name: 'Qena' },
      { id: 'Qena', name: 'New Qena' },
      { id: 'Qena', name: 'Abu Tesht' },
      { id: 'Qena', name: 'Nag Hammadi' },
      { id: 'Qena', name: 'Deshna' },
      { id: 'Qena', name: 'Alwaqf' },
      { id: 'Qena', name: 'Qaft' },
      { id: 'Qena', name: 'Naqada' },
      { id: 'Qena', name: 'Farshout' },
      { id: 'Qena', name: 'Quos' },
      { id: 'North Sinai', name: 'Arish' },
      { id: 'North Sinai', name: 'Sheikh Zowaid' },
      { id: 'North Sinai', name: 'Nakhl' },
      { id: 'North Sinai', name: 'Rafah' },
      { id: 'North Sinai', name: 'Bir al-Abed' },
      { id: 'North Sinai', name: 'Al Hasana' },
      { id: 'Sohag', name: 'Sohag' },
      { id: 'Sohag', name: 'Sohag El Gedida' },
      { id: 'Sohag', name: 'Akhmeem' },
      { id: 'Sohag', name: 'Akhmim El Gedida' },
      { id: 'Sohag', name: 'Albalina' },
      { id: 'Sohag', name: 'El Maragha' },
      { id: 'Sohag', name: "almunsha'a" },
      { id: 'Sohag', name: 'Dar AISalaam' },
      { id: 'Sohag', name: 'Gerga' },
      { id: 'Sohag', name: 'Jahina Al Gharbia' },
      { id: 'Sohag', name: 'Saqilatuh' },
      { id: 'Sohag', name: 'Tama' },
      { id: 'Sohag', name: 'Tahta' },
      { id: 'Sohag', name: 'Alkawthar' },
    ];
  }

  Brand() {
    return [
      {
        id: 'laptop',
        label: 'laptop',
        img: '../../assets/img/laptop.png',
        items: [
          {
            id: 'msi',
            label: 'MSI',
            img: '../../assets/brandIcons/msi.png',
          },
          { id: 'hp', label: 'hp', img: '../../assets/brandIcons/hp.png' },
          {
            id: 'lenovo',
            label: 'Lenovo',
            img: '../../assets/brandIcons/lenovo.png',
          },
          {
            id: 'dell',
            label: 'Dell',
            img: '../../assets/brandIcons/dell.png',
          },
          {
            id: 'acer',
            label: 'Acer',
            img: '../../assets/brandIcons/acer.png',
          },
          {
            id: 'asus',
            label: 'Asus',
            img: '../../assets/brandIcons/asus.png',
          },
        ],
      },
      {
        id: 'mobile',
        label: 'mobile',
        img: '../../assets/img/smartphone.png',
        items: [
          {
            id: 'samsung',
            label: 'Samsung',
            img: '../../assets/brandIcons/samsung.png',
          },
          {
            id: 'realme',
            label: 'Realme',
            img: '../../assets/brandIcons/realme.png',
          },
          {
            id: 'honor',
            label: 'Honor',
            img: '../../assets/brandIcons/honor.png',
          },
          {
            id: 'huawei',
            label: 'Huawei',
            img: '../../assets/brandIcons/huawei.png',
          },
          {
            id: 'xiaomi',
            label: 'Xiaomi',
            img: '../../assets/brandIcons/xiaomi.png',
          },
          {
            id: 'oppo',
            label: 'Oppo',
            img: '../../assets/brandIcons/oppo.png',
          },
        ],
      },
    ];
  }
    

  Model() {
    return [
      {
        type: 'laptop',
        id: 'acer',
        label: 'acer',
        img: '../../assets/brandIcons/acer.png',
        items: [
          { id: 'aspire3-a315-notebook', img: 'aspire3-a315-notebook.jpg', label: 'Aspire 3  A315' },
          { id: 'aspire5-notebook', img: 'aspire5-notebook.jpg', label: 'Aspire 5 Notebook' },
          { id: 'nitro5-an515', img: 'nitro5-an515.jpg', label: 'Nitro 5 AN515' },
          { id: 'predator-helios', img: 'predator-helios.jpg', label: 'Predator Helios' },
          { id: 'swift5', img: 'swift5.jpg', label: 'Swift 5' },
        ],
      },

      {
        type: 'laptop',
        id: 'asus',
        label: 'asus',
        img: '../../assets/brandIcons/asus.png',
        items: [
          { id: 'expertbook', img: 'expertbook.jpg', label: 'Expertbook' },
          { id: 'tuf-dash-f15', img: 'tuf-dash-f15.jpg', label: 'TUF Dash 15' },
          { id: 'vivobook15', img: 'vivobook15.jpg', label: 'Vivobook 15' },
          { id: 'zenbook13', img: 'zenbook13.jpg', label: 'Zenbook 13' },
        ],
      },

      {
        type: 'laptop',
        id: 'dell',
        label: 'dell',
        img: '../../assets/brandIcons/dell.png',
        items: [
          { id: 'g3', img: 'g3.jpg', label: 'G3' },
          { id: 'g15', img: 'g15.jpg', label: 'G15' },
          { id: 'inspiron7405', img: 'inspiron7405.jpg', label: 'Inspiron 7405' },
          { id: 'latitude3520', img: 'latitude3520.jpg', label: 'Latitude 3520' },
          { id: 'vostro3500', img: 'vostro3500.jpg', label: 'Vostro 3500' },
        ],
      },

      {
        type: 'laptop',
        id: 'hp',
        label: 'hp',
        img: '../../assets/brandIcons/hp.png',
        items: [
          { id: 'envy-x360', img: 'envy-x360.jpg', label: 'Envy X360' },
          { id: 'g7', img: 'g7.jpg', label: 'G7' },
          { id: 'pavilion15', img: 'pavilion15.jpg', label: 'Pavilion 15' },
          { id: 'victus16', img: 'victus16.jpg', label: 'Victus 16' },
        ],
      },

      {
        type: 'laptop',
        id: 'lenovo',
        label: 'lenovo',
        img: '../../assets/brandIcons/lenovo.png',
        items: [
          { id: 'ideapad5', img: 'ideapad5.jpg', label: 'Ideapad 5' },
          { id: 'ideapad-flex5', img: 'ideapad-flex5.jpg', label: 'Ideapad Flex 5' },
          { id: 'legion5', img: 'legion5.jpg', label: 'Legion 5' },
          { id: 'v15', img: 'v15.jpg', label: 'V15' },
          { id: 'yoga7', img: 'yoga7.jpg', label: 'Yoga 7' },
        ],
      },

      {
        type: 'laptop',
        id: 'msi',
        label: 'msi',
        img: '../../assets/brandIcons/msi.png',
        items: [
          { id: 'gaming-gs76', img: 'gaming-gs76.jpg', label: 'Gaming GS76' },
          { id: 'gf63', img: 'gf63.jpg', label: 'GF63' },
          { id: 'gf65', img: 'gf65.jpg', label: 'GF65' },
          { id: 'modern14', img: 'modern14.jpg', label: 'Modern 14' },
          { id: 'sword15"', img: 'sword15.jpg', label: 'Sword 15' },
        ],
      },

      {
        type: 'mobile',
        id: 'samsung',
        label: 'samsung',
        img: '../../assets/brandIcons/samsung.png',
        items: [
          { id: 'a12', img: 'a12.png', label: 'A12' },
          { id: 'a33', img: 'a33.png', label: 'A33' },
          { id: 'a52', img: 'a52.png', label: 'A52' },
          { id: 'a72', img: 'a72.png', label: 'A72' },
          { id: 'galaxy-note7', img: 'galaxy-note7.png', label: 'Galaxy Note 7' },
          { id: 'galaxy-note8', img: 'galaxy-note8.png', label: 'Galaxy Note 8' },
          { id: 'galaxy-note9', img: 'galaxy-note9.png', label: 'Galaxy Note 9' },
          { id: 'm31', img: 'm31.png', label: 'M31' },
          { id: 's20', img: 's20.png', label: 'S20' },
          { id: 's21', img: 's21.png', label: 'S21' },
        ],
      },
      {
        type: 'mobile',
        id: 'realme',
        label: 'realme',
        img: '../../assets/brandIcons/oppo.png',
        items: [
          { id: '6', img: '6.png', label: 'Realme 6' },
          { id: '6i', img: '6i.png', label: 'Realme 6I' },
          { id: '7', img: '7.png', label: 'Realme 7' },
          { id: '7pro', img: '7pro.png', label: 'Realme 7 PRO' },
          { id: '8pro', img: '8pro.png', label: 'Realme 8 PRO' },
          { id: 'c11', img: 'c11.png', label: 'Realme C11' },
          { id: 'c15', img: 'c15.png', label: 'Realme C15' },
          { id: 'c25', img: 'c25.png', label: 'Realme C25' }, // score
        ],
      },
      {
        type: 'mobile',
        id: 'honor',
        label: 'honor',
        items: [
          { id: '8a', img: '8a.png', label: 'Honor 8A' },
          { id: '8x', img: '8x.png', label: 'Honor 8X' },
          { id: '9x-pro', img: '9x-pro.png', label: 'Honor 9X PRO' },
        ],
      },
      {
        type: 'mobile',
        id: 'huawei',
        label: 'huawei',
        img: '../../assets/img/huawei.png',
        items: [
          { id: 'nova8', img: 'nova8.png', label: 'Nova 8' },
          { id: 'p30-pro', img: 'p30-pro.png', label: 'P30 PRO' },
          { id: 'P40-pro', img: 'p40-pro.png', label: 'P40 PRO' },
          { id: 'y7-prime', img: 'y7-prime2019.png', label: 'Y7 Prime' }, //score
        ],
      },
      {
        type: 'mobile',
        id: 'xiaomi',
        label: 'xiaomi',
        img: '../../assets/img/xiaomi.png',
        items: [
          { id: '9a', img: '9a.png', label: 'Xiaomi 9A' },
          { id: '9c', img: '9c.png', label: 'Xiaomi 9C'},
          { id: 'mi-9t', img: '9t.png', label: 'Mi 9T' }, //score
          { id: 'note7', img: 'note7.png', label: 'Note 7' },
          { id: 'note8', img: 'note8.png', label: 'Note 8' },
          { id: 'note9s', img: 'note9s.png', label: 'Note 9S' },
          { id: 'note10', img: 'note10.png', label: 'Note 10' },
          { id: 'note10-pro', img: 'note10-pro.png', label: 'Note 10 PRO' },
          { id: 'note11', img: 'note11.png', label: 'Note 11' },
          { id: 'note11-pro', img: 'note11-pro.png', label: 'Note 11 PRO' },
          { id: 'poco-f1', img: 'poco-f1.png', label: 'POCO F1' },
          { id: 'poco-x3', img: 'poco-x3.png', label: 'POCO X3' },
        ],
      },
      {
        type: 'mobile',
        id: 'oppo',
        label: 'oppo',
        img: '../../assets/img/oppo.png',
        items: [
          { id: 'a12', img: 'a12.png', label: 'Oppo A12' },
          { id: 'a54', img: 'a54.png', label: 'Oppo A54' },
          { id: 'a74', img: 'a74.png', label: 'Oppo A74' },
          { id: 'reno2-Z', img: 'reno2-z.png', label: 'Reno 2Z' },
          { id: 'reno4', img: 'reno4.png', label: 'Reno 4' },
        ],
      },
    ];
  }

  Type() {
    return [
      { id: 'laptop', name: 'Laptop' },
      { id: 'mobile', name: 'Mobile' },
    ];
  }

  Color() { 
    return [
      { name: 'black', icon: 'Black' },
      { name: 'white', icon: 'White' },
      { name: 'silver', icon: 'Silver' },
      { name: 'red', icon: 'Red' },
      { name: 'blue', icon: 'Blue' },
      { name: 'mint green', icon: '#A2E4B8' },
      { name: 'purple', icon: 'Purple' },
    ];
  }
  RAM() { 
    return [
      { name: '4GB', value: 4 },
      { name: '6GB', value: 6 },
      { name: '8GB', value: 8 },
      { name: '16GB', value: 16 },
    ];
  }
  ROM() {
    return [
      { name: '16GB', value: 16 },
      { name: '32GB', value: 32 },
      { name: '64GB', value: 64 },
      { name: '128GB', value: 128 },
      { name: '256GB', value: 256 },
    ];
  }

}
